export const STUDENT_ADD_REQUESTED = 'STUDENT_ADD_REQUESTED';
export const STUDENT_ADD_STARTED = 'STUDENT_ADD_STARTED';
export const STUDENT_ADD_FAILED = 'STUDENT_ADD_FAILED';
export const STUDENT_ADD_FINISHED = 'STUDENT_ADD_FINISHED';

export const STUDENT_LIST_REQUESTED = 'STUDENT_LIST_REQUESTED';
export const STUDENT_LIST_STARTED = 'STUDENT_LIST_STARTED';
export const STUDENT_LIST_FAILED = 'STUDENT_LIST_FAILED';
export const STUDENT_LIST_FINISHED = 'STUDENT_LIST_FINISHED';

export const STUDENT_GET = 'STUDENT_GET';